### PR TITLE
Issue 292: Updating js-yaml to fix audit errors

### PR DESCRIPTION
**Pull request by jumde**
fix https://github.com/brave/sync/issues/292

### CODE REVIEW

**Comment by diracdeltas** [comment]
@SergeyZhukovsky please merge this if it looks good to you

**Comment by bbondy** [comment]
it's the cause of busted CI builds so I'm going to vouch and merge.

**Comment by diracdeltas** [comment]
please also open this against master @jumde

**Comment by jumde** [comment]
@diracdeltas - https://github.com/brave/sync/pull/295

**Pull request merged**
