### PR TITLE
Proprogate seed info to maybeSetDeviceId

### PR DESCRIPTION
**Pull request by darkdh**
fix https://github.com/brave/sync/issues/221

### CODE REVIEW

**Comment by darkdh** [comment]
addressed in b5fd36340689854f3199fe1ca7af21f5741a6be8

**Comment by diracdeltas** [comment]
lint is failing

**Comment by darkdh** [comment]
one is `/home/travis/build/brave/sync/client/sync.js:24:5: It's not necessary to initialize 'seed' to undefined.`

**Comment by diracdeltas** [comment]
@darkdh you can just do `var seed` without setting a value

**Comment by darkdh** [comment]
yep, fixed in 0fcb89f81fa52e046b98f099fe8828cf335a4309

**Pull request merged**
