### PR TITLE
Use public interface to get signing seed length

### PR DESCRIPTION
**Pull request by dchest**

### CODE REVIEW

**Comment by ayumi** [comment]
Thank you for the patch :)
I saw the tests failed in Travis, so I ran them locally and they passed.

@diracdeltas could you have a look?

**Comment by diracdeltas** [comment]
they also passed locally for me

**Comment by diracdeltas** [comment]
i've restarted the Travis build 3 times and each time it failed with:
```
# client RequestUtil
# constructor
Connecting to http://localhost:4000
not ok 30 Error: Credential server response 500
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      [Error: Credential server response 500]
    at: Test.assert [as _assert] (http://localhost:40495/bundle.js:47:28326)
    stack: |-
      Error: Credential server response 500
          at window.fetch.then.response (http://localhost:40495/bundle.js:52:20779)
  ...
```

so it doesn't seem to be an intermittent fail. i have no idea how this change could lead to that error. :/

**Comment by diracdeltas** [comment]
Somehow, https://github.com/brave/sync/pull/36 passes even though it is the exact same change :/. I am going to close this PR in favor of that. :crystal_ball: :ghost: #GreatUnsolvedMysteries

**Comment by ayumi** [comment]
@diracdeltas We use travis encrypted env vars to do the AWS tests, which for security only work when collaborators initiate the build.

**Comment by diracdeltas** [comment]
@ayumi o i c

i assume the merged branches will pass Travis since merge commits are done by collaborators, but is there a way to fix it so that outside contributor PR's don't always show up as failing?

**Pull request closed without merging**
