### PR TITLE
Fix vulnerability (remove coverage task)

### PR DESCRIPTION
**Pull request by bsclifton**
This resolves vulnerability with handlebars by removing the `coverage` task and dependency

### CODE REVIEW

**Comment by diracdeltas** [comment]
dupe of #336 ?

**Comment by bsclifton** [comment]
@diracdeltas this is for `master`; #336 is for `staging` actually

**Comment by bsclifton** [comment]
Closing as coverage is needed for CI

**Comment by diracdeltas** [comment]
@bsclifton sorry my bad - didn't see that they were for different branches

**Pull request closed without merging**
