### PR TITLE
Changes to speed up polling new records

### LINKED ISSUE #228: Polling bookmarks records is slow
We can make changes to poll the corresponding queue till we have messages there

### PR DESCRIPTION
**Pull request by SergeyZhukovsky**
closes #228

### CODE REVIEW

**Comment by diracdeltas** [comment]
it would be good to have an automated test for this

**Comment by SergeyZhukovsky** [comment]
Yep we have an issue for that https://github.com/brave/sync/issues/220. Do you have any idea how it could be tested? Well I can create a simple notification on a test bucket and call the API to poll it, but it will not really cover the scenario with Amazon servers peak times sometimes.

**Comment by SergeyZhukovsky** [comment]
I propose we prioritize #220 and make the tests in a separate PR instead of blocking the fix of existing functionality.

**Comment by diracdeltas** [comment]
yeah, i think it would be good for just having basic SQS functionality tests to make sure that updates don't break anything (since i don't know how to test this manually right now). probably no need to test for performance right now.

**Pull request merged**
