### PR TITLE
Fix vulnerability preventing Desktop from building

### PR DESCRIPTION
**Pull request by bsclifton**
Helps fix brave/brave-browser#4075

### CODE REVIEW

**Comment by diracdeltas** [comment]
How were these changes generated?

**Comment by AlexeyBarabash** [comment]
@diracdeltas I guess, with `npm audit fix`
before PR
```
npm install

> electron@1.8.8 postinstall /home/alexey/Projects/sync_CLIFTON/sync/node_modules/electron
> node install.js


> nodemon@1.18.6 postinstall /home/alexey/Projects/sync_CLIFTON/sync/node_modules/nodemon
> node bin/postinstall || exit 0


> protobufjs@6.8.8 postinstall /home/alexey/Projects/sync_CLIFTON/sync/node_modules/protobufjs
> node scripts/postinstall

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 796 packages from 636 contributors and audited 4378 packages in 8.329s
found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

alexey@HAPPYUBU7:~/Projects/sync_CLIFTON/sync$ npm audit 
                                                                                
                       === npm audit security report ===                        
                                                                                
# Run  npm update tar --depth 5  to resolve 1 vulnerability
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary File Overwrite                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ tar                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ nodemon [dev]                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ nodemon > chokidar > fsevents > node-pre-gyp > tar           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/803                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

after PR

```
git checkout fced1236e01e9cdd0630712468362be42d9d9d62
Note: checking out 'fced1236e01e9cdd0630712468362be42d9d9d62'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at fced123... Fix vulnerability preventing Desktop from building
alexey@HAPPYUBU7:~/Projects/sync_CLIFTON/sync$ npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 4378 packages in 3.841s
```

**Comment by diracdeltas** [comment]
sgtm

**Comment by bsclifton** [comment]
That is correct- this is the result from running `npm audit fix`

**Pull request merged**
